CREATE TABLE uzytkownicy(
   id INT AUTO_INCREMENT UNIQUE PRIMARY KEY,
   login VARCHAR(50) UNIQUE NOT NULL,
   haslo VARCHAR(100) NOT NULL
);

CREATE TABLE maszyny(
   id INT AUTO_INCREMENT UNIQUE PRIMARY KEY,
   nazwaMaszyny VARCHAR(100) UNIQUE NOT NULL,
   idUzytkownika INT NOT NULL
);